server:
  port: 8081

spring:
  application:
    name: match-service

  datasource:
    url: jdbc:postgresql://localhost:5433/sportsscoredb
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # automatically create db tables
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
